### ISSUE TITLE
problem when creating AVD

### ISSUE THREAD

**Issue by Zar86** [trevjonez/AVD-Gradle-Plugin#2]
Hi, Trevor Jones!
When using `abi 'armeabi-v7a'` in build.gradle.
```
AVD {
    acceptAndroidSdkLicense true
    acceptAndroidSdkPreviewLicense true
    configs {
        tablet_25 {
            avd {
                api 25
                type 'google_apis'
                abi 'armeabi-v7a'
                deviceId 'Nexus 5X'
            }
            launchOption("-no-audio")
            launchOption("-no-window")
        }
    }
}
```

Run task installSystemImage_api25_GoogleApis_arm
`./gradlew installSystemImage_api25_GoogleApis_arm`

Gives an error message:
> Starting process: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager system-images;android-25;google_apis;arm
> **
> **
> **
> stdErr: Warning: Failed to find package system-images;android-25;google_apis;arm
> stdErr threw: sdkmanager install
> Disposing: /home/vagrant/android-sdk-linux/tools/bin/sdkmanager system-images;android-25;google_apis;arm
> 

The same problems exist if I use `armeabi, armeabi-v7a, arm64-v8a, mips, mips64`.
If I use `abi 'x86'` or` abi 'x86_64'`, then everything is fine!
Thanks in advance!

**Comment by trevjonez** [comment]
looks like I am pulling the wrong field from the abi enum. going to tag a 0.2.1 with a fix right now.

**Comment by trevjonez** [comment]
https://github.com/trevjonez/AVD-Gradle-Plugin/releases/tag/0.2.1

keep me posted on how it goes. I have only attempted to test on osx although I expect an appropriately configured linux environment should just work. all bets off with windows I think though.

**Comment by Zar86** [comment]
Thanks for the quick response!
Now this problem appeared in the `Task: createAvd_tablet_25`
> Starting process: /home/vagrant/android-sdk-linux/tools/bin/avdmanager create avd --name tablet_25 --package system-images;android-25;google_apis;arm --device Nexus 5X
> avdmanager create avd threw
> Disposing: /home/vagrant/android-sdk-linux/tools/bin/avdmanager create avd --name tablet_25 --package system-images;android-25;google_apis;arm --device Nexus 5X

Thanks in advance!

**Comment by trevjonez** [comment]
I had some copy pasted code for that image key string. few more minutes to verify I have the install file paths correct for task status checks and I'll tag a 0.2.2

**Comment by trevjonez** [comment]
https://github.com/trevjonez/AVD-Gradle-Plugin/releases/tag/0.2.2

give that a try.

**Comment by Zar86** [comment]
> Error:Could not find com.github.trevjonez:AVD-Gradle-Plugin:0.2.2.
> Searched in the following locations:
>     file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.pom
>     file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.jar
>     https://jcenter.bintray.com/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.pom
>     https://jcenter.bintray.com/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.jar
>     https://jitpack.io/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.pom
>     https://jitpack.io/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.jar
>     https://maven.fabric.io/public/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.pom
>     https://maven.fabric.io/public/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.jar
>     https://plugins.gradle.org/m2/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.pom
>     https://plugins.gradle.org/m2/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.jar
>     https://dl.google.com/dl/android/maven2/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.pom
>     https://dl.google.com/dl/android/maven2/com/github/trevjonez/AVD-Gradle-Plugin/0.2.2/AVD-Gradle-Plugin-0.2.2.jar
> Required by:
>     project :

**Comment by trevjonez** [comment]
jitpack had a timeout. I just forced it to rebuild.

**Comment by Zar86** [comment]
Thank you, Trevor Jones! Now everything works correctly. Thanks for a quick fix to this problem!

**Comment by trevjonez** [comment]
NP thanks for giving it a spin. you helped surface a number of issues.
