### ISSUE TITLE
Problem when moving code from 'build.gradle' to 'app:build.gradle'

### ISSUE THREAD

**Issue by Zar86** [trevjonez/AVD-Gradle-Plugin#4]
Hi, Trevor Jones!
the structure of my project is as follows:
```
/project
---/app
------/src
------build.gradle (app:build.gradle)
---build.gradle (build.gradle)
---local.properties
```
in file **build.gradle** the following is written:
``` groovy
...
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath "com.github.trevjonez:AVD-Gradle-Plugin:0.3.0"
    }
}
...   
apply plugin: 'AVD'
AVD {
    configs {
        tablet_25 {
            avd {
                api 25
                type 'google_apis'
                abi 'x86'
            }
        }
    }
}
```
The project is not a problem!
but if I transfer part 
```  groovy
apply plugin: 'AVD'
AVD {
    configs {
        tablet_25 {
            avd {
                api 25
                type 'google_apis'
                abi 'x86'
            }
        }
    }
}
``` 
to file **app:build.gradle**, then I get an error when I call any task:
Gradle sync failed: Unable to find android sdk. Specify ANDROID_HOME env variable or sdk.dir in **local.properties**.
As if the of this plugin makes the subproject **'app'** the root project.

Thanks in advance!

**Comment by trevjonez** [comment]
ah yes I am likely looking directly at the project the plugin is applied against. I'll add some dispatching so that it will look at the parent chain before it fails.

**Comment by trevjonez** [comment]
@Zar86 feel free to review that PR for me so we can get the new build out asap.

**Comment by Zar86** [comment]
Thanks for the prompt decision of a problem!
