### ISSUE TITLE
Update Plugin

### ISSUE THREAD

**Issue by Zar86** [trevjonez/AVD-Gradle-Plugin#7]
Hi, Trevor Jones!
will update plugin according to android new api?
Thanks in advance!

**Comment by trevjonez** [comment]
as far as I know it should still work with the latest plugin version. I'll try to set some time aside this week to update and test everything in the repo.

**Comment by trevjonez** [comment]
use 0.5.0 and let me know if you have any further issues. sorry for the delay.
